version: '3.1'
services:
  # docker run -d --name db -e POSTGRES_USER=odoo_user -e POSTGRES_PASSWORD=odoo -e POSTGRES_DB=db_dev -v ${PWD}/pgdata:/data -v ${PWD}/config:/config/ -p 5433:5432 postgres:14
  db:
    container_name: db
    image: postgres:14
    user: root
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo_user
      - POSTGRES_DB=db_dev
      - PGDATA=/data
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_WAL_LEVEL=db_replica
      - POSTGRES_MAX_WAL_SENDERS=5
      - POSTGRES_WAL_KEEP_SEGMENTS=32
    ports:
      - "5433:5432"
    restart: always             # run as a service
    volumes:
      - ./config:/config/
      - ./pgdata:/data

  db_replica:
    container_name: db_replica
    image: postgres:14.0
    user: root
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo_user
      - POSTGRES_DB=db_dev
      - PGDATA=/data_replica
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_REPLICA_FROM=db
    ports:
      - "5434:5432"
    restart: always
    networks:
      - odoo-web
    volumes:
      - ./config:/config/
      - ./pgdata_replica:/data_replica

  # docker run -p 10012:8069 --name odoo --link db:db -t odoo:12.0
  web-odoo-one:
    container_name: odoo-one
    image: odoo:12.0
    user: root
    depends_on:
      - db
    ports:
      - "10012:8069"
      - "20012:8072" # live chat
    tty: true
    # command: --
    command: >
            odoo --db_host=db --db_user=odoo_user --db_password=odoo --db_port=5432 -d db_dev --http-interface=0.0.0.0 --http-port=8069 -i base
#    command: odoo scaffold /mnt/extra-addons/test_module
    environment:
      - HOST=db
      - USER=odoo_user
      - PASSWORD=odoo
      - DATABASE=db_dev
    networks:
      - odoo-web
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      # - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
    restart: always             # run as a service

networks:
  odoo-web:
    driver: bridge

volumes:
  odoo-web-data:
